name: Instagram Trending Nightly

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch: {}

jobs:
  trending:
    runs-on: ubuntu-latest
    env:
      IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
      IG_USER_ID: ${{ secrets.IG_USER_ID }}
      IG_TREND_TAGS: ${{ vars.IG_TREND_TAGS }}
      MAX_DAILY_DOWNLOADS: ${{ vars.MAX_DAILY_DOWNLOADS }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp python-dotenv

      - name: Run Instagram trending fetch
        run: |
          python -m python.instagram.trending

      - name: Convert to planner artifacts
        run: |
          python -m python.instagram.convert_to_planner

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Build planner
        working-directory: go
        run: go build -o bin/planner ./cmd/planner

      - name: Run planner (schedule posts)
        working-directory: go
        run: |
          ./bin/planner --trends ../_data/trends.json --variants ../_data/variants.json --spacing 2h --start-offset 30m

